// === COLORS ===
export const COLORS = {
  STONE_DARK: 0x4a4038,
  STONE_MID: 0x5a5048,
  STONE_LIGHT: 0x6a6058,
  STONE_FLOOR: 0x3a3530,
  WOOD_DARK: 0x3a2818,
  WOOD_PEW: 0x4a3820,
  IRON: 0x4a4a4a,
  IRON_RUST: 0x5a4a3a,
  CANDLE_WAX: 0xd4c4a0,
  CANDLE_FLAME: 0xffaa44,
  CANDLE_LIGHT: 0xff9933,
  LANTERN_LIGHT: 0xffcc77,
  CRIMSON: 0x8a2b2b,
  CRIMSON_DARK: 0x4a1515,
  CRIMSON_GLOW: 0xcc3333,
  GREEN_SICK: 0x3a5a2a,
  GREEN_GLOW: 0x44ff44,
  BONE: 0xd4c8a0,
  BONE_DARK: 0x8a7a5a,
  GLASS_RED: 0x881111,
  GLASS_BLUE: 0x112255,
  GLASS_AMBER: 0x884411,
  GLASS_GREEN: 0x115522,
  FOG: 0x0a0908,
  AMBIENT: 0x332838,
  ARTIFACT_GLOW: 0xcc8844,
};

// === DIMENSIONS ===
export const CATHEDRAL = {
  NAVE_LENGTH: 60,
  NAVE_WIDTH: 16,
  NAVE_HEIGHT: 18,
  AISLE_WIDTH: 5,
  PILLAR_RADIUS: 0.6,
  PILLAR_SPACING: 8,
  WALL_THICKNESS: 1.5,
  ARCH_HEIGHT: 14,
  CEILING_HEIGHT: 18,
  APSE_DEPTH: 12,
  APSE_WIDTH: 12,
  CHAPEL_WIDTH: 6,
  CHAPEL_DEPTH: 5,
  TOWER_SIZE: 5,
  TOWER_HEIGHT: 30,
};

export const CRYPT = {
  LENGTH: 40,
  WIDTH: 20,
  HEIGHT: 4,
  CORRIDOR_WIDTH: 3,
  CHAMBER_SIZE: 6,
};

// === PLAYER ===
export const PLAYER = {
  HEIGHT: 1.7,
  CROUCH_HEIGHT: 0.9,
  SPEED: 2.5,
  CROUCH_SPEED: 1.2,
  MOUSE_SENSITIVITY: 0.002,
  HEAD_BOB_SPEED: 8,
  HEAD_BOB_AMOUNT: 0.04,
  SWAY_SPEED: 0.5,
  SWAY_AMOUNT: 0.003,
  COLLISION_RADIUS: 0.4,
  INTERACT_DISTANCE: 3.0,
};

// === SANITY ===
export const SANITY = {
  MAX: 100,
  DARKNESS_DRAIN: 3,      // per second
  WARDEN_LOOK_DRAIN: 15,  // per second
  ARTIFACT_DRAIN: 20,     // instant
  WHISPER_DRAIN: 5,       // per event
  CANDLE_RESTORE: 4,      // per second
  NOTE_RESTORE: 10,       // instant
  TIER_NORMAL: 75,
  TIER_UNEASY: 50,
  TIER_DISTURBED: 25,
  TIER_MADNESS: 0,
};

// === WARDEN ===
export const WARDEN = {
  SPEED_PATROL: 1.5,
  SPEED_PURSUIT: 3.5,
  DETECTION_RANGE: 20,
  DETECTION_ANGLE: Math.PI / 3,   // 60 degree cone
  SOUND_RANGE_WALK: 12,
  SOUND_RANGE_CROUCH: 4,
  LOSE_INTEREST_TIME: 8,
  HEIGHT: 2.8,
  KILL_RANGE: 1.5,
  HUM_MAX_DISTANCE: 30,
};

// === LIGHTING ===
export const LIGHTING = {
  CANDLE_INTENSITY_MIN: 0.8,
  CANDLE_INTENSITY_MAX: 1.8,
  CANDLE_FLICKER_SPEED: 0.1,
  CANDLE_DISTANCE: 16,
  LANTERN_INTENSITY: 3.0,
  LANTERN_DISTANCE: 22,
  LANTERN_SWAY_SPEED: 2,
  LANTERN_SWAY_AMOUNT: 0.15,
  SHADOW_MAP_SIZE: 1024,
};

// === GAME STATE ===
export const GAME_STATE = {
  LOADING: 'loading',
  MENU: 'menu',
  PLAYING: 'playing',
  PAUSED: 'paused',
  NOTE_READING: 'reading',
  DEATH: 'death',
  WIN: 'win',
};
